// Command protocolgen generates Go packet catalogs from the authoritative C# attributes.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type packet struct {
	Direction, Name   string
	ID, Length        uint64
	UseInt, Encrypted bool
}

var (
	attributeRE = regexp.MustCompile(`(?s)\[PacketInfo(?:Attribute)?\s*\((.*?)\)\]`)
	sourceRE    = regexp.MustCompile(`Source\s*=\s*PacketSource\.(Client|Server)`)
	idRE        = regexp.MustCompile(`Id\s*=\s*(\d+)`)
	lengthRE    = regexp.MustCompile(`Length\s*=\s*(\d+)`)
	classRE     = regexp.MustCompile(`(?s)(?:public\s+)?(?:sealed\s+)?class\s+([^\s:{]+)`)
)

func main() {
	root := flag.String("root", ".", "repository root")
	out := flag.String("out", "internal/gameprotocol/catalog_gen.go", "output path")
	flag.Parse()
	packets, err := scan(*root)
	if err != nil {
		panic(err)
	}
	if err := write(*out, packets); err != nil {
		panic(err)
	}
}
func scan(root string) ([]packet, error) {
	var packets []packet
	for _, location := range []string{"GamePackets/Client", "GamePackets/Server", "GamePackets/UnknownPackets.cs"} {
		path := filepath.Join(root, location)
		info, err := os.Stat(path)
		if err != nil {
			return nil, err
		}
		var files []string
		if info.IsDir() {
			matches, _ := filepath.Glob(filepath.Join(path, "*.cs"))
			files = matches
		} else {
			files = []string{path}
		}
		for _, file := range files {
			data, err := os.ReadFile(file)
			if err != nil {
				return nil, err
			}
			matches := attributeRE.FindAllSubmatchIndex(data, -1)
			for i, match := range matches {
				attrs := data[match[2]:match[3]]
				source, id, length := sourceRE.FindSubmatch(attrs), idRE.FindSubmatch(attrs), lengthRE.FindSubmatch(attrs)
				if source == nil || id == nil || length == nil {
					continue
				}
				end := len(data)
				if i+1 < len(matches) {
					end = matches[i+1][0]
				}
				body := data[match[1]:end]
				class := classRE.FindSubmatch(body)
				if class == nil {
					return nil, fmt.Errorf("class not found after attribute in %s", file)
				}
				idValue, _ := strconv.ParseUint(string(id[1]), 10, 16)
				lengthValue, _ := strconv.ParseUint(string(length[1]), 10, 32)
				packets = append(packets, packet{Direction: string(source[1]), Name: string(class[1]), ID: idValue, Length: lengthValue, UseInt: bytes.Contains(attrs, []byte("UseIntSize = true")), Encrypted: !bytes.Contains(body, []byte("Encrypted = false")) && !bytes.Contains(body, []byte("Encrypted=false"))})
			}
		}
	}
	sort.Slice(packets, func(i, j int) bool {
		if packets[i].Direction == packets[j].Direction {
			return packets[i].ID < packets[j].ID
		}
		return packets[i].Direction < packets[j].Direction
	})
	seen := map[string]bool{}
	for _, p := range packets {
		key := fmt.Sprintf("%s:%d", p.Direction, p.ID)
		if seen[key] {
			return nil, fmt.Errorf("duplicate packet %s", key)
		}
		seen[key] = true
	}
	return packets, nil
}
func write(path string, packets []packet) error {
	var out strings.Builder
	out.WriteString("// Code generated by protocolgen; DO NOT EDIT.\npackage gameprotocol\n\n")
	for _, direction := range []string{"Client", "Server"} {
		fmt.Fprintf(&out, "var %sPackets = map[uint16]Descriptor{\n", direction)
		for _, p := range packets {
			if p.Direction != direction {
				continue
			}
			fmt.Fprintf(&out, "%d: {ID: %d, Length: %d, Name: %q, UseIntSize: %t, Encrypted: %t},\n", p.ID, p.ID, p.Length, p.Name, p.UseInt, p.Encrypted)
		}
		out.WriteString("}\n\n")
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return fmt.Errorf("format output: %w\n%s", err, out.String())
	}
	return os.WriteFile(path, formatted, 0o644)
}
